# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rvaz-da- <rvaz-da-@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/08/16 22:18:28 by rvaz-da-          #+#    #+#              #
#    Updated: 2025/08/16 22:21:14 by rvaz-da-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file.a

SRC = main.c display_file.c error_messages.c

FLAGS = -Werror -Wextra -Wall

OBJ = $(SRC:.c=.o)

RM = rm -f

all: $(NAME)

